### ISSUE TITLE
[ROS2] Consider branching out to `dashing-devel`

### ISSUE THREAD

**Issue by Karsten1987** [ros-visualization/rqt_publisher#10]
Given the latest changes in ROS2 for the dashing release, I believe it makes sense to branch out to a `dashing-devel` branch.

One of the changing is for example the exposure of `history-depth` as a QoS.

**Comment by dirk-thomas** [comment]
Until there is a change proposed in a PR which is necessary for Dashing but not compatible with Crystal there is no need for branching.
