### ISSUE TITLE
[ROS2][RQT_PUBLISHER] types are not displayed correctly

### ISSUE THREAD

**Issue by Karsten1987** [ros-visualization/rqt_publisher#14]
There is a mismatch in the types. When choosing the type of the message, it's getting displayed without the newly introduced `msg` or `srv` middle part of it. However,  when restarting, the latest added publisher has the correct type assigned.

See the following screenshot for clarity.
<img width="969" alt="Screen Shot 2019-05-28 at 4 05 13 PM" src="https://user-images.githubusercontent.com/5419873/58518087-a23a0400-8162-11e9-910a-24e455a48b4a.png">

**Comment by dirk-thomas** [comment]
Resolved by #15.
