### ISSUE TITLE
ROS2: Cannot set/publish JointState with user-specified values

### ISSUE THREAD

**Issue by kschwan** [ros-visualization/rqt_publisher#34]
Hi,
On Ubuntu 22.04 with ROS2 Humble I'm unable to publish sensor_msgs/msg/JointState with user-specified values. I suppose this might be related to #27, #28.

This is what I'm publishing:
![Screenshot from 2022-09-21 14-29-53](https://user-images.githubusercontent.com/821793/191503988-8e6dbffc-7784-4fe9-af87-aa7f7428c80e.png)

And this is what I'm receiving (note that the std_msgs/msg/Bool seems to be working).
```
$ ros2 topic echo --once /test
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: ''
name: []
position: []
velocity: []
effort: []
---
```

```
$ ros2 topic echo --once /test2
data: true
---
```

Package version:
```
$ apt show ros-humble-rqt-publisher 
Package: ros-humble-rqt-publisher
Version: 1.5.0-1jammy.20220909.020605
Priority: optional
Section: misc
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Installed-Size: 109 kB
Depends: python3-catkin-pkg-modules, ros-humble-python-qt-binding (>= 0.2.19), ros-humble-qt-gui-py-common, ros-humble-rqt-gui, ros-humble-rqt-gui-py, ros-humble-rqt-py-common, ros-humble-ros-workspace
Homepage: http://wiki.ros.org/rqt_publisher
Download-Size: 23.8 kB
APT-Manual-Installed: no
APT-Sources: http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages
Description: rqt_publisher provides a GUI plugin for publishing arbitrary messages with fixed or computed field values.
```

**Comment by kschwan** [comment]
I didn't notice that I was getting this error from rqt_publisher

```
[ERROR] [1663763988.089399671] [get_message_class]: Malformed message_type: sequence<string>
Traceback (most recent call last):
  File "/opt/ros/humble/lib/python3.10/site-packages/rqt_publisher/publisher.py", line 161, in change_publisher
    new_text = handler(self._publishers[publisher_id], topic_name, new_value)
  File "/opt/ros/humble/lib/python3.10/site-packages/rqt_publisher/publisher.py", line 244, in _change_publisher_expression
    success, _ = self._evaluate_expression(expression, slot_type)
  File "/opt/ros/humble/lib/python3.10/site-packages/rqt_publisher/publisher.py", line 329, in _evaluate_expression
    if successful_eval and isinstance(value, slot_type):
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

**Comment by gbiggs** [comment]
Could you try Rolling and see if the same bug is present there as well?

**Comment by kschwan** [comment]
> Could you try Rolling and see if the same bug is present there as well?

Sure! Thanks for the suggestion.

If I type in a `list` in the position expression, I get the error shown in the screenshot below. If I type in an `array.array`, it works.

![Screenshot from 2022-09-29 09-56-22](https://user-images.githubusercontent.com/821793/192973915-a75ede54-43c3-4e15-b4e2-97d59a59a448.png)

**Comment by gbiggs** [comment]
Are you happy with that solution?

**Comment by kschwan** [comment]
> Are you happy with that solution?

Yes, I'm fine using rolling and typing in an array.array, thanks! It would be nice if typing in a list would work too though -- that's how it was on ROS1.

**Comment by clalancette** [comment]
> Yes, I'm fine using rolling and typing in an array.array, thanks! It would be nice if typing in a list would work too though -- that's how it was on ROS1.

Yeah, I agree, that would be much nicer.  I did some work on this earlier this year, but I never got it completed.  Hopefully I can find some time to complete that.

That said, this is similar in spirit to #23.  @gbiggs I'm not sure if you want to close #23 (since technically that one works now) and leave this one open, or vice-versa.  Either is fine with me.

**Comment by gbiggs** [comment]
I'll close this one, since the other looks like it still has proposed changes that haven't been PR'd.
